"""empty message

Revision ID: 1106fdb4f377
Revises: 0b6fd44a745a
Create Date: 2023-01-26 16:30:25.834176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1106fdb4f377'
down_revision = '0b6fd44a745a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favoritos', schema=None) as batch_op:
        batch_op.drop_column('favoritos_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favoritos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favoritos_id', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
