"""empty message

Revision ID: 771052d2d844
Revises: 1106fdb4f377
Create Date: 2023-01-26 16:31:25.762942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '771052d2d844'
down_revision = '1106fdb4f377'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personajes', schema=None) as batch_op:
        batch_op.drop_column('perosnajes_id')

    with op.batch_alter_table('planetas', schema=None) as batch_op:
        batch_op.drop_column('planetas_id')

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('usuario_id')

    with op.batch_alter_table('vehiculos', schema=None) as batch_op:
        batch_op.drop_column('vehiculos_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehiculos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehiculos_id', sa.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('planetas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planetas_id', sa.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('personajes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('perosnajes_id', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
